### ISSUE TITLE
issue opening image

### ISSUE THREAD

**Issue by ktyssowski** [paucabar/AimSeg#1]
this tool seems very useful! however, after following the setup instructions with no issue, i'm having an issue when i go to open an image. the log reads:
```
[ERROR] org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
AimSeg/AimSeg_.groovy: 96: unable to resolve class inra.ijpb.label.edit.ReplaceLabelValues
 @ line 96, column 1.
   import inra.ijpb.label.edit.ReplaceLabelValues
   ^

AimSeg/AimSeg_.groovy: 95: unable to resolve class inra.ijpb.watershed.MarkerControlledWatershedTransform2D
 @ line 95, column 1.
   import inra.ijpb.watershed.MarkerControlledWatershedTransform2D
   ^

AimSeg/AimSeg_.groovy: 83: unable to resolve class org.ilastik.ilastik4ij.hdf5.Hdf5DataSetReader
 @ line 83, column 1.
   import org.ilastik.ilastik4ij.hdf5.Hdf5DataSetReader
   ^

AimSeg/AimSeg_.groovy: 362: unable to resolve class BinaryReconstruct_
 @ line 362, column 28.
       def BinaryReconstruct_ br = new BinaryReconstruct_()
                              ^

AimSeg/AimSeg_.groovy: 362: unable to resolve class BinaryReconstruct_
 @ line 362, column 33.
       def BinaryReconstruct_ br = new BinaryReconstruct_()
                                   ^

5 errors

	at org.codehaus.groovy.control.ErrorCollector.failIfErrors(ErrorCollector.java:295)
	at org.codehaus.groovy.control.CompilationUnit$ISourceUnitOperation.doPhaseOperation(CompilationUnit.java:893)
	at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:623)
	at groovy.lang.GroovyClassLoader.doParseClass(GroovyClassLoader.java:389)
	at groovy.lang.GroovyClassLoader.lambda$parseClass$3(GroovyClassLoader.java:332)
	at org.codehaus.groovy.runtime.memoize.StampedCommonCache.compute(StampedCommonCache.java:163)
	at org.codehaus.groovy.runtime.memoize.StampedCommonCache.getAndPut(StampedCommonCache.java:154)
	at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:330)
	at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:314)
	at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:257)
	at org.codehaus.groovy.jsr223.GroovyScriptEngineImpl.getScriptClass(GroovyScriptEngineImpl.java:336)
	at org.codehaus.groovy.jsr223.GroovyScriptEngineImpl.eval(GroovyScriptEngineImpl.java:153)
	at org.scijava.plugins.scripting.groovy.GroovyScriptLanguage$1.eval(GroovyScriptLanguage.java:97)
	at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:264)
	at org.scijava.script.ScriptModule.run(ScriptModule.java:173)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:165)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:125)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:64)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:247)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)

```

i'm running it on a mac with an M1 chip OS12.3, with the lasted beta version of illastik1.4.1b7-arm64-OSX (not sure if that is the issue? -- do i need older illastik?)

**Comment by ktyssowski** [comment]
ok i figured out some of the error was due to not having all the plugins updated. i've now done that, but still am getting the following error when I try to preprocess:

`[ERROR] java.lang.ArrayIndexOutOfBoundsException: 1
	at ij.process.ByteProcessor.resize(ByteProcessor.java:1045)
	at ij.process.ImageProcessor.resize(ImageProcessor.java:2308)
	at ij.plugin.Scaler.createNewStack(Scaler.java:127)
	at ij.plugin.Scaler.resize(Scaler.java:100)
	at ij.ImagePlus.resize(ImagePlus.java:2535)
	at ij.ImagePlus.resize(ImagePlus.java:2527)
	at ij.ImagePlus$resize$2.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:157)
	at Pre-processing_.resizeImage(Pre-processing_.groovy:27)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1262)
	at groovy.lang.DelegatingMetaClass.invokeMethod(DelegatingMetaClass.java:226)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:61)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:171)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:194)
	at Pre-processing_.preProcessing(Pre-processing_.groovy:45)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1262)
	at groovy.lang.DelegatingMetaClass.invokeMethod(DelegatingMetaClass.java:226)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:61)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:171)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:203)
	at Pre-processing_.run(Pre-processing_.groovy:76)
	at org.codehaus.groovy.jsr223.GroovyScriptEngineImpl.eval(GroovyScriptEngineImpl.java:317)
	at org.codehaus.groovy.jsr223.GroovyScriptEngineImpl.eval(GroovyScriptEngineImpl.java:155)
	at org.scijava.plugins.scripting.groovy.GroovyScriptLanguage$1.eval(GroovyScriptLanguage.java:97)
	at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:264)
	at org.scijava.script.ScriptModule.run(ScriptModule.java:173)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:165)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:125)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:64)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:247)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
`

**Comment by paucabar** [comment]
Thank you very much for reporting the issue. I'm not sure where the problem lies. Could you please describe the steps that led to you encountering this error?
Just to make sure, are you using the main AimSeg script or the pre-processing one?

**Comment by ktyssowski** [comment]
I think I figured out the problem:
The downsample default is 0, but since downsampling is multiplying by whatever that value is, if it's 0, it won't work. I changed it to 1 and it works. (this was the pre-process script)

I had another issue when running plugins --> Aimseg -->Aimseg, which is that despite having and updating the ilastik imagej plugin, it can't find the hd5 file reader. i commented that out of the source code (since i exported from ilastik as tifs, as recommended), and now things are working ok.

**Comment by paucabar** [comment]
Thanks for all the info.

> The downsample default is 0, but since downsampling is multiplying by whatever that value is, if it's 0, it won't work. I changed it to 1 and it works. (this was the pre-process script).

True, I've modified the script, so it's not possible to use 0 and corrected the defaults.

> I had another issue when running plugins --> Aimseg --> Aimseg, which is that despite having and updating the ilastik ImageJ plugin, it can't find the HDF5 file reader. I commented that out of the source code (since I exported from ilastik as tifs, as recommended), and now things are working ok.

I have replaced the HDF5 reader, which seems to be deprecated.

Updating your AimSeg version should solve all the issues, hopefully :)
